### ISSUE TITLE
The bot doesn't link articles with multiple slashes at the beginning

### ISSUE THREAD

**Issue by betseg** [stjohann/DiscordWikiBot#24]
The bot handles single slash with articles like [/dev/random](https://en.wikipedia.org/wiki//dev/random) but it doesn't understand [//](https://en.wikipedia.org/wiki///) or [//Khara Hais Local Municipality](https://en.wikipedia.org/wiki///Khara_Hais_Local_Municipality).

Link to message in Wikimedia Discord: [link](https://discord.com/channels/221049808784326656/221060705078476801/1072234998951854172)

**Comment by stjohann** [comment]
Forgot to leave any comment about this: `[[//Khara Hais Local Municipality]]` is not a valid wikilink even in English Wikipedia, so that’s why WikiBot does not treat it as a valid wikilink. `[//example.com]` syntax is typically used for protocol-relative links in MediaWiki and that’s probably not going to change any time soon (although those links are becoming more rare due to HTTPS-only restrictions that Wikimedia projects have).

I don’t think any change is needed in this case, to accommodate what must be an extremely small subset of articles that probably shouldn’t be named that way to begin with. For those reasons, this is not a bug and will not be fixed.
